"""Reports: POST /reports, GET /reports/{id}, GET /reports/{id}/download (api.md §28).

PDF via ReportLab: executive summary + device + compliance + CVE + PQC +
security + remediation + evidence. PDFs bytes live in Postgres (reports.pdf).
"""
from __future__ import annotations
import io
from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel
from typing import List

from app.core import config as cfg
from app.core import persist as db
from app.core import store

router = APIRouter(prefix="/api/v1/reports", tags=["reports"])


class ReportBody(BaseModel):
    audit_id: str
    format: str = "PDF"
    sections: List[str] = ["EXECUTIVE_SUMMARY", "DEVICE", "COMPLIANCE", "CVE", "PQC", "SECURITY", "REMEDIATION", "EVIDENCE"]


def _build_pdf(audit: dict) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib import colors
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=15 * mm, bottomMargin=15 * mm)
    styles = getSampleStyleSheet()
    story = []
    s = audit["summary"]
    asset = db.get("assets", audit.get("asset_id", "")) or {}
    vend = audit.get("vendor") or {}
    story += [Paragraph("Network Security Compliance Audit Report", styles["Title"]),
              Paragraph("Device Identification", styles["Heading2"]),
              Paragraph(f"Asset {audit['asset_id']} · {asset.get('name', '')} · "
                        f"Vendor {vend.get('vendor', 'unknown')} · Platform {vend.get('platform', 'unknown')} · "
                        f"Version {vend.get('version', '') or asset.get('version', '')} · "
                        f"Model {asset.get('model', '')} · Serial {asset.get('serial_number', '')} · "
                        f"IP {asset.get('ip_address', '')} · Env {asset.get('environment', '')} · "
                        f"Criticality {asset.get('criticality', '')}", styles["Normal"]),
              Spacer(1, 6)]
    story.append(Paragraph(
        f"Compliance {s.get('compliance_score')}% · Critical {s.get('CRITICAL', 0)} · "
        f"High {s.get('HIGH', 0)} · Medium {s.get('MEDIUM', 0)} · Low {s.get('LOW', 0)} · "
        f"CVE vulnerable {audit['cve']['summary'].get('vulnerable', 0)} · "
        f"PQC readiness {audit['pqc'].get('readiness_score')}", styles["Normal"]))
    story.append(Spacer(1, 8))
    rows = [["Finding", "Sev", "Status", "Title"]]
    for f in audit["findings"][:80]:
        rows.append([f.get("finding_id", ""), str(f.get("severity", "")),
                     str(f.get("status", "")), str(f.get("title", ""))[:90]])
    t = Table(rows, repeatRows=1, colWidths=[28 * mm, 18 * mm, 18 * mm, 110 * mm])
    t.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2a37")),
                           ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                           ("FONTSIZE", (0, 0), (-1, -1), 8),
                           ("GRID", (0, 0), (-1, -1), 0.4, colors.grey)]))
    story += [Paragraph("Findings (first 80)", styles["Heading2"]), t, Spacer(1, 8),
              Paragraph("Generated by SIH-26155 auditor (simulation; remediation requires human approval).",
                        styles["Normal"])]
    doc.build(story)
    return buf.getvalue()


@router.post("")
def create_report(body: ReportBody):
    audit = db.get("audits", body.audit_id)
    if not audit:
        raise HTTPException(404, "Audit not found")
    rid = store.nid("REP")
    pdf = _build_pdf(audit)
    db.save("reports", {"report_id": rid, "audit_id": body.audit_id, "status": "COMPLETED",
                        "format": body.format, "sections": body.sections,
                        "download_url": f"/api/v1/reports/{rid}/download", "pdf": pdf,
                        "created_at": store.now()})
    return cfg.ok({"report_id": rid, "status": "COMPLETED",
                   "download_url": f"/api/v1/reports/{rid}/download"}, "Report generated")


@router.get("/{report_id}")
def get_report(report_id: str):
    r = db.get("reports", report_id)
    if not r:
        raise HTTPException(404, "Report not found")
    return cfg.ok({"report_id": report_id, "status": r["status"],
                   "download_url": r["download_url"]})


@router.get("/{report_id}/download")
def download_report(report_id: str):
    r = db.get("reports", report_id)
    if not r:
        raise HTTPException(404, "Report not found")
    return Response(content=r["pdf"], media_type="application/pdf",
                    headers={"Content-Disposition": f"attachment; filename={report_id}.pdf"})
